# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_course_arrangement?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Chq.5247L247
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 热部署配置
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  #设置文件传输大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.chq.coursearrange.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #不删除

server:
  port: 8080


# 阿里云OSS
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-shenzhen.aliyuncs.com
#      accessKeyId: 你们自己的key
#      accessKeySecret: 你们自己的密钥
#      bucketName: arrange